### ISSUE TITLE
bs4 missing?

### ISSUE THREAD

**Issue by mfreeman72** [mathsgrinds/ustvnow-iptv-m3u-playlist#1]
I'm trying to run your script, and I get this:

`Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from bs4 import BeautifulSoup
ImportError: No module named bs4`

I'm running Linux Mint 18.

I have the package python-beautifulsoup installed. Is there something else I need?

**Comment by mathsgrinds** [comment]
Hi, yeah I have this problem with Python sometimes. I have a module installed but it is not running it. I have found two common reasons for it:

1)      The package name might be a bit different like “import bs4” or “import beautifulsoup” or “import BeautifulSoup4” etc

2)      The second problem is sometimes I have to “force” python to look in a particular folder to find it, like with, 

import sys

reload(sys)

sys.path.append("/usr/lib/python2.7/dist-packages")

sys.path.append("/usr/local/lib/python2.7/dist-packages")

I’m not sure which of the two problems you might be having J let me know how you get on please!!

**Comment by mfreeman72** [comment]
Thanks for the help! I replaced bs4 with BeautifulSoup, and it worked.

Now for the next problem: The streams won't play. I believe it's due to 
my lack of understanding on how the script handles login information. 
Could you please give tell me the syntax and location(s) for entering my 
login/password into the script?

Thank you!

**Comment by mfreeman72** [comment]
Never mind. I figured it out, and now the script works great! Thanks!
