### ISSUE TITLE
am i doing something wrong? cant get script to work

### ISSUE THREAD

**Issue by Wolverine2018** [mathsgrinds/ustvnow-iptv-m3u-playlist#10]
hi, is script working? i get the following errors

Traceback (most recent call last):
File "main.py", line 98, in 
Ustvnow(username, password)
File "main.py", line 62, in Ustvnow
j = json.loads(html)
File "/usr/lib/python2.7/json/init.py", line 338, in loads
return _default_decoder.decode(s)
File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by mathsgrinds** [comment]
Strange, I’ll have a look sometime, the addon USTVNOW # is still working so I don’t know why the scraper broken since my addon uses my scraper :P

I’ll investigate.

PS: I assumed you used a known and working username and password?

**Comment by Wolverine2018** [comment]
hi, thanks for your prompt reply, yes its a newly created account so user and pass all good.i am able to log into their website ok using my email address.

Sent from my iPad

On 8 Aug 2017, at 00:08, MathsGrinds <notifications@github.com<mailto:notifications@github.com>> wrote:

Strange, I’ll have a look sometime, the addon USTVNOW # is still working so I don’t know why the scraper broken since my addon uses my scraper :P

I’ll investigate.

PS: I assumed you used a known and working username and password?

**Comment by jacknight** [comment]
When I see that error, it’s because my username and password are incorrect, that would have been my first guess as well.  Worth mentioning that the script just pulled the stream links fine for me.

Jack

**Comment by Wolverine2018** [comment]
i must be missing something then guys. i tried applying user pass and ALL via command line and also within the python file. i did originally sign up with google plus then i reset password to login directly to site

Sent from my iPad

On 8 Aug 2017, at 10:41, Jack Knight <notifications@github.com<mailto:notifications@github.com>> wrote:

When I see that error, it’s because my username and password are incorrect, that would have been my first guess as well. Worth mentioning that the script just pulled the stream links fine for me.

Jack

**Comment by mathsgrinds** [comment]
Okay, I'll have a look when I get home, thanks for letting me know!

**Comment by Wolverine2018** [comment]
i just redownloaded from your github and put username and pass within py file again. its now got slightly further. now getting list index out of range after retrieving some url's

[image1.PNG]

Sent from my iPad

On 8 Aug 2017, at 10:56, MathsGrinds <notifications@github.com<mailto:notifications@github.com>> wrote:

Okay, I'll have a look when I get home, thanks for letting me know!

**Comment by Wolverine2018** [comment]
how can i get the ts links as a playlist please guys?

Sent from my iPad

On 8 Aug 2017, at 10:56, MathsGrinds <notifications@github.com<mailto:notifications@github.com>> wrote:

Okay, I'll have a look when I get home, thanks for letting me know!

**Comment by jacknight** [comment]
just run the command with > your_playlist.m3u at the end
python main.py > wolverine2018.m3u


Jack

**Comment by Wolverine2018** [comment]
i did, doesn't give the .ts  extension on each so my app doesn't recognise them as transport streams

Sent from my iPad

On 8 Aug 2017, at 13:48, Jack Knight <notifications@github.com<mailto:notifications@github.com>> wrote:

just run the command with > your_playlist.m3u at the end
python main.py > wolverine2018.m3u


Jack

**Comment by Wolverine2018** [comment]
ok if i open the m3u8, for each channel they play but from main playlist they don't? any way to extract top link for each channel automatically? i've used wget so far to download  each channel m3u

Sent from my iPad

On 8 Aug 2017, at 13:48, Jack Knight <notifications@github.com<mailto:notifications@github.com>> wrote:

just run the command with > your_playlist.m3u at the end
python main.py > wolverine2018.m3u


Jack

**Comment by Wolverine2018** [comment]
if i send you a list of a few channels in a bit can you check they work from the links your script generates pls?

**Comment by Wolverine2018** [comment]
Animal Planet
ESPN2
Freeform
MSNBC USA

**Comment by mathsgrinds** [comment]
Hi guys, sorry I’m coming to this late, is the idea that we’d like the code modified to return the dot TS file?

**Comment by Wolverine2018** [comment]
yes please. also have you tested how many streams can be run consecutively?  some  streams drop out and i have to renew the tokens. 

also is there a way of only generating the 1280 x 720p as a playlist?

**Comment by mathsgrinds** [comment]
I’ve updated the code to allow for printing of the TS link and printing of the HD link.

Thanks.

**Comment by mathsgrinds** [comment]
Okay, so is it cool to close this issue now?

**Comment by Wolverine2018** [comment]
sorry man i meant to reply, i'm getting access denied for the links. was generated from same public ip as im trying to run streams from

Sent from my iPad

On 13 Aug 2017, at 11:41, MathsGrinds <notifications@github.com<mailto:notifications@github.com>> wrote:


Okay, so is it cool to close this issue now?

**Comment by mathsgrinds** [comment]
Strange, when I run the python code with my username and password in it it give me the TS links, are you getting an access denied error when you run the code?

**Comment by Wolverine2018** [comment]
i get the links with no extension. gives links ok but when i access them its forbidden

Sent from my iPad

On 13 Aug 2017, at 19:19, MathsGrinds <notifications@github.com<mailto:notifications@github.com>> wrote:

Strange, when I run the python code with my username and password in it it give me the TS links, are you getting an access denied error when you run the code?

**Comment by mathsgrinds** [comment]
Do you mind sending me a link to examine please?

**Comment by Wolverine2018** [comment]
sure. how can i message you directly?

Sent from my iPad

On 13 Aug 2017, at 19:40, MathsGrinds <notifications@github.com<mailto:notifications@github.com>> wrote:

Do you mind sending me a link to examine please?

**Comment by mathsgrinds** [comment]
No problem, can you send a direct message in github?

**Comment by mathsgrinds** [comment]
Just contact me using my contact details on my home page J

**Comment by mathsgrinds** [comment]
Hi all, I’ve updated the code as some users have reported their generated links not working. But it came at the expense of choosing TS over m3u8 and HD over SD.
