### ISSUE TITLE
ImportError: No module named requests

### ISSUE THREAD

**Issue by unixjeff** [mathsgrinds/ustvnow-iptv-m3u-playlist#11]
I edited the main.py added my user and pass then ran "python main.py" and got the error below any ideas?
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    import requests
ImportError: No module named requests

Ubuntu with python (2.7.11-1).

**Comment by mathsgrinds** [comment]
Hi there, you are missing that module on your computer. And will need to install it.
