### ISSUE TITLE
Getting Errors

### ISSUE THREAD

**Issue by jctennis** [mathsgrinds/ustvnow-iptv-m3u-playlist#13]
This was working fantastically this morning for my paid USTVnow subscription. Now when I run it I am getting the following errors:

Traceback (most recent call last):
  File "C:\Users\kodi\Downloads\ustvm3u.py", line 150, in <module>
    result = Ustvnow(username, password)
  File "C:\Users\kodi\Downloads\ustvm3u.py", line 123, in Ustvnow
    result += "#EXTINF:-1,"+stream_code+" - "+title+"\n"
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 12: ordinal not in range(128)

I have my credentials entered directly into the script, but if I try and call them from outside the script the output is "False".

Any Ideas?

**Comment by mathsgrinds** [comment]
Update is on its way in the next few minutes.

**Comment by AgileHumor** [comment]
You rock MathGrinds!  Thank you for sharing this project.

**Comment by mathsgrinds** [comment]
Great, I assume the update worked :)
