### ISSUE TITLE
Request Explicit/Filtered Channel List in Single M3U File

### ISSUE THREAD

**Issue by AgileHumor** [mathsgrinds/ustvnow-iptv-m3u-playlist#16]
For some reason, about 6 channels will not load in Kodi (i.e. FreeForm).  I signed up with a new account, same issue.

Is there a way that these channels can be tested or worked.
OR
Can I create a SINGLE M3U file with certain channels (essentially listing all those that work, minus the ones not working).

This is important as the Kodi IPTV client needs a single M3U.  The current code only lets you create a separate M3U for each file.

Thanks!

**Comment by mathsgrinds** [comment]
Updated code should fix this

**Comment by AgileHumor** [comment]
Thx
