### ISSUE TITLE
Still working March 2018?

### ISSUE THREAD

**Issue by gigi66** [mathsgrinds/ustvnow-iptv-m3u-playlist#17]
Hello there,

First of all, I want to thank you for this script, very useful with my custom Kodi setup (intel nuc), I was using it for the past 3 months successfully.

Do you think is there any issues with the links it generates, for the past 2 or 3 days it stopped working in Kodi and when I try a generated link in VLC it fails to play.

This is the link I get that fails to play in VLC:
http://ilvc05.ec.ustvnow.com/ilv01/pr/xxe/smil:DBBA7WGALUSTVNOW/playlist.m3u8?f1a2823da53acb9b9d726286209af87f2333d3ba6a878f736caf3a754ff6ef77584f2a5be4c93d52852c72f562c853c82ac0d3f28e6bfaf2bb55f200

Thanks!

**Comment by michlinux** [comment]
#18 
Submitted a pull request to fix this... or you can just take from my fork when its accepted.
https://github.com/michlinux/ustvnow-iptv-m3u-playlist

**Comment by mathsgrinds** [comment]
yep yep
