### ISSUE TITLE
Links on USTVNOW expire  inside a day?

### ISSUE THREAD

**Issue by markosjal** [mathsgrinds/ustvnow-iptv-m3u-playlist#19]
Do these links to USTVNOW expire ? It seemsed they worked till about midnight Eastern Time, then died.

If so is there any way to automate the script on Android every hour?

Is the scrript compatible with Python 2 and 3?

**Comment by mathsgrinds** [comment]
Hi there, yes they expire once per 24 hours. You would need to rerun the script to get the fresh links.

**Comment by markosjal** [comment]
Any idea how to automate this on Android? It was an elegant solution how I had it working wirth IPTV Client but seems impossible to keep it going regularly without some server elsewhere to do the processing, and that represents a security issue.

**Comment by mathsgrinds** [comment]
How are you importing them into android?

**Comment by markosjal** [comment]
Copied via USB Memory. Unfortunately where I wanted USTVNOW there is not a computer there and I see no secure method to get them to an android IPTV client over the web.

Would be best to have a Cron on Android running the python commant. Everything I see about python on android seems very convoluted and nothing seems to be script-able

**Comment by mathsgrinds** [comment]
I'm afraid I wouldn't know what is best for you to do. The links are valid for less than 24 hours, this is out of my control
