### ISSUE TITLE
now getting non-working links

### ISSUE THREAD

**Issue by markosjal** [mathsgrinds/ustvnow-iptv-m3u-playlist#20]
I was testing this on a local ubuntu machine and yesterday and got vailid lnks that worked till about midnight Eastern Time (USA) 

Tonight i run the script from my server and the links appear to be generated , and then they are downloaded on android perfect player (currently over http) , but none work.

I tested the Perfect Player on android with a different list and same delivery method, and it works.. I also copied the generated lists to a USB memory and they still do not work.

**Comment by markosjal** [comment]
Ok I made a discovery that is relevant to this bug. I can now reproduce it as follows

Ubuntu 16.04 x64
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Links generated work fine

Ubuntu 16.04 32bit
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Gives me non-functional links.

**Comment by markosjal** [comment]
ok, now I can not get valid links out of EITHER system! I think the script is broken and I just lost 3 days on this.

**Comment by mathsgrinds** [comment]
Okay but you know I don't work for USTVNOW, I just cobbled together a script for myself which usually works that I decided to share online because there isn't one out there.

**Comment by markosjal** [comment]
I know you do not . I am trying to help us MUTUALLY. Sorry If I seem rude. It is not my intention.

I have new info as to this problem. It does seem to be a 32 vs 64 bit issue as I originally posted . Today I had a file that was not overwriting

I have 2 files generated in the last few minute I would like to get to you one was generated on one system and another on a different system, one works one does not.  Even the file size is different.

**Comment by mathsgrinds** [comment]
Hi there, I am totally perplexed by this, I can’t see why being 32 bit or 64 bit would affect the python script scraping the links. It would be like if it running on windows on linux caused a difference. Unless something is being sent in the header? I could force the header if you like, if the 64 bit version works for you then tell me the header which is sent and I can make the header that.

**Comment by michlinux** [comment]
What client are you using? I noticed ustvnow seams to have blocked VLC sometime in the last month. Resulting in an error: "http stream error: error: HTTP/1.1 403 Client not supported" If that is your problem then changing vlc's user-agent will let you bypass this block.
[https://wiki.videolan.org/HTTP/](https://wiki.videolan.org/HTTP/)

**Comment by michlinux** [comment]
I've test it on x86_64(fedora 28), armv7l (Ubuntu 16.04 & Debian 9), armv5tel(Custom Linux), and mips(Custom Linux)... produces usable urls on all of them for me.. tested with Streamlink & ffmpeg, tested free account and my paid account. all of them work.

**Comment by markosjal** [comment]
Michlinux, YOU ARE CORRECT. My error was that I was unaware that I needed to run the script on my same IP as the player that plays the video. The links are vailid only to the IP making the query.

Now I need to run it on android!
