### ISSUE TITLE
Please create an option to sanitize channel name.

### ISSUE THREAD

**Issue by markosjal** [mathsgrinds/ustvnow-iptv-m3u-playlist#21]
from my playlist file:
#EXTINF:-1,ESPN - NBA Basketball

Can you please create an option to sanize the channel name by deleting " - NBA Basketball" or " - *"
under the current scenario it is impossible to sync channels to guide info

**Comment by markosjal** [comment]
I found one python exaple here
https://unix.stackexchange.com/questions/257514/how-to-delete-the-rest-of-each-line-after-a-certain-pattern-or-a-string-in-a-fil

**Comment by mathsgrinds** [comment]
Done in latest update
