### ISSUE TITLE
Running on Pyton 3 Android

### ISSUE THREAD

**Issue by markosjal** [mathsgrinds/ustvnow-iptv-m3u-playlist#22]
Trying to run on Python 3 from Qpython3 for Android, gives me the following error...

__________________________
Error Line 76
print csrf
            ^
SyntaxError :  invalid syntax
______________________________

The "^" seems to point at the "f"

Is the code not Python 3 compatible?

Any recommendations for Python android?

QPython2 is not compatible with my android device.

BTW , My Irish friend would love it if I can find non-geo blocked Ireland streams other than RTE News Now.

Thanks,

Mark

**Comment by mathsgrinds** [comment]
I think it is print(csrf) in python 3. If I recall you can run something like 2to3 on the file to update it. PS: Tunnel bear is a good VPN to use for that stuff
