### ISSUE TITLE
external variables file

### ISSUE THREAD

**Issue by markosjal** [mathsgrinds/ustvnow-iptv-m3u-playlist#23]
Since I do not know python, I wanted to ask, how I might create an external variables file for username and passwword in ustvnow-iptv-m4u-playlist, as I tried to pass the external variables from a shell script and it seems to not work (only gives me free channels for a paid account) . might you have some insight that you would share?

Thanks
Mark

**Comment by mathsgrinds** [comment]
I'm afraid I don't follow

**Comment by markosjal** [comment]
i figured this out. I now created a text file with USTVNow username and password. Your script now imports this file, so changing it just got easier ,  thanks anyway
