### ISSUE TITLE
Bug "hide Title Variable"

### ISSUE THREAD

**Issue by markosjal** [mathsgrinds/ustvnow-iptv-m3u-playlist#24]
I believe you mean in the script below instead of
    hideTitle = sys.argv[4]             

should be

    hideTitle = sys.argv[5]             

---------------------------------------------------------------------------------------------------------------------------

try:
    username = sys.argv[1]
except:
    username = ""                       # Set username manually here if not using the command line

try:
    password = sys.argv[2]
except:
    password = ""                       # Set username manually here if not using the command line

try:
    channel = sys.argv[3]
except:
    channel = "ALL"                     # Set channel manually here if not using the command line (use ALL to show all)

try:
    CreateSTRM = sys.argv[4]
except:
    CreateSTRM = False                  # Set if you would like to create the STRM file

try:
    hideTitle = sys.argv[4]             
except:
    hideTitle = True                    # For those of you who would like to hide the showing now show title

**Comment by mathsgrinds** [comment]
Cheers
