### ISSUE TITLE
Only pulling streams for 3 channels

### ISSUE THREAD

**Issue by daviem** [mathsgrinds/ustvnow-iptv-m3u-playlist#25]
Hi, with the script I can only get the links for ABC, CBS & CW, the script is set at ALL but stops running after getting the 3 links, what could be wrong?

**Comment by drwggm** [comment]
Not sure what's going on, but if you replace the

```
except: 
    break
```

with 

```
except:
    print 'something broke'
```

around line 132, it will dump all channels.

**Comment by mathsgrinds** [comment]
That is freaking weird.
