### ISSUE TITLE
New script return else

### ISSUE THREAD

**Issue by daviem** [mathsgrinds/ustvnow-iptv-m3u-playlist#4]
Hi, I would like to start by saying thanks for your script :), the only issue I have is I keep getting the else response but no streams generated, on the old script I would get the streams written to a file, what could be causing this?

**Comment by mathsgrinds** [comment]
Hi David, thanks, I’ll look into this, I might return it to the old way of doing things, someone suggested this as an improvement. I’ll check this out later, now I’m off to the dentist. :P

**Comment by mathsgrinds** [comment]
I have made changes to the script which I think has resolved it for you :)

**Comment by mathsgrinds** [comment]
Hi David, all good now?

**Comment by daviem** [comment]
Hey :), thanks for altering the script :), I cant check it right now I need to access the machine from another pc its behind a second router the one I have the script installed on but I will definitely check it out today or tomoz, cheers and get back to you, thanks again!

**Comment by daviem** [comment]
Okay, I tested your script on a couple of machines, and its perfect in function thank you, however I tried it with a free account and a paid one, there was an issue with the paid one, it returned links starting with

axp.ustvnow.com%3A80%2Fi%2F6F6D8WHP0USTVNOW_DEF%40190604%2Fmaster.m3u8%3Fhdnea%3Dip%3D24.24.142.32%7Est%3D1451602800%7Eexp%3D1451631600%7Eacl%3D%2F

apx being the issue as none of the streams work, I dont think its the script as it worked perfectly on the other account, so Im wondering if its something that ustvnow have done?

Thanks again btw

**Comment by mathsgrinds** [comment]
Hi, yeah, the problem is I don't have a paid account so I'm not sure
how to scrape those links, someone added in the paid channels to my
script but in my original it was only the free ones. I could change the
code so that those types of links are skipped when scanning for video
links. But I'm afraid without a paid account I wouldn't be confident in
getting it to work :) sorry

**Comment by maaamark** [comment]
The original script works fine. daviem... notice in your link 24.24.142.32. The paid streams are tied to your public ip address. if you try to access or play them from outside (Even if you VPN into the network) they will not play. the "axp" urls are an authentication url. if you run the script again in a couple hours from the same machine, the querry will populate the usual urls as your ip address is already cached. They expire every few hours, so you need to re-run to re-authenticate
Use the ORIGINAL script that mathsgrind 1st wrote. add the rest of the channels "EXACTLY as below. Even if you miss a capital or a space, it wont work" 

 def Ustvnow(user, password, stations=["ABC", "CBS", "CW", "FOX", "NBC", "PBS", "My9", "AETV", "AMC", "Animal Planet", "Bravo", "Cartoon Network", "CNBC", "CNN", "Comedy Central", "Discovery Channel", "ESPN", "Fox News Channel", "FX", "History", "Lifetime", "National Geographic Channel", "Nickelodeon", "SPIKE TV", "Syfy", "TBS", "TNT", "USA"]):

Hope this helps

**Comment by daviem** [comment]
Hi guys, thank you both, I will try  adding the channels you listed maaamark thanks!, I will also test your new script mathsgrinds to see if it works too with the paid channels :)

**Comment by daviem** [comment]
well its been a while and I was wondering if I can get any help guys, its been over a month and I still cant get the links for the pay account to work, adding 

def Ustvnow(user, password, stations=["ABC", "CBS", "CW", "FOX", "NBC", "PBS", "My9", "AETV", "AMC", "Animal Planet", "Bravo", "Cartoon Network", "CNBC", "CNN", "Comedy Central", "Discovery Channel", "ESPN", "Fox News Channel", "FX", "History", "Lifetime", "National Geographic Channel", "Nickelodeon", "SPIKE TV", "Syfy", "TBS", "TNT", "USA"]):

generates the streams but the streams wont play, I also noticed a new hmac field, not sure f that is having an affect? 

Tried on the device it was generated on and on other devices, no go, using a free account it works so...

http://ilvc02.ak.ustvnow.com/ilv10/pr/xal/smil:00000NICKUSTVNOW/playlist.m3u8?hdnts=st=1485291600~exp=1485320400~acl=/*~hmac=42d881b2a651c971d20b09be5a0531c091301991d0040a3bb88ce6155b800204&j=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuIjoiMTZhOWVkIiwidCI6Im80dnU2bmdkejdraDk4eGJsbndvZHV6YXprD4WiLCJpIjoiZDVjZGZjNDgiLCJzIjoibmlja2Vsb2Rlb24ifQ.tv_hUSR67X-dABplzJw12CAsWJwlzDUQbrxQd_NJ0LI

**Comment by mathsgrinds** [comment]
Hi daviem. I don’t have a paid account so I can’t test out what changes might be required. I can only tinker with my free account. If any user with a paid account can spot a fix to your problem and pushes the changes to me I can update the script.

**Comment by daviem** [comment]
Hi mathsgrinda, Do the links generated still work for you using VLC? I just tried my free account again and those links though in a different format wont play for me anymore either, also I have no issues letting you access my paid account if it would help.

**Comment by mathsgrinds** [comment]
Odd. I just used it a few days ago to watch something when the addon wasn't working.

---- On Wed, 25 Jan 2017 07:06:06 +0000 notifications@github.com wrote ----

Hi mathsgrinda, Do the links generated still work for you using VLC? I just tried my free account again and those links though in a different format wont play for me anymore either, also I have no issues letting you access my paid account if it would help.

**Comment by daviem** [comment]
I know I had used it before commenting yesterday and it was working so I thought I would try getting the pay version to work, then I went back to the free version and tried on a couple of linux machines and the links wouldnt work in VLC. Im hoping they are just having technical problems and it will be fixed.

**Comment by daviem** [comment]
Ok well the free channels are working again, the paid ones still dont, however I analysed the difference between the working paid url from the addon and the one the script produces that doesnt work, the difference is basically the token and the ip address is inside the link, so the link has to be tied to your ip address heres an example if it helps...

none working link for tnt

http://ilvc01.ak.ustvnow.com/ilv61/pr/xal/smil:4AE8ETNT0USTVNOW/playlist.m3u8?hdnts=st=1485604800~exp=1485633600~acl=/*~hmac=65ac69dae149be1fed17a9815c5f098fbc50d973a0bc8a9daa1e91bdf091e091ca60761&jwt=eyJ0eZAiOiLKV1AiLCJhbGciOiJIUzI1NiJ9.eyJuIjoiMTZhYjMzIiwidCI6Im80dnA2bmdkejdraCk4eGJsbndvZHV0AXprZ3AiLCJpIjoiMWY1YjQxMzIiLCJzIjoidG50In0.K18GLySeP8-liH4w00ZmTaAbgCVbwhJTPR-vPspqZrY

working link from tnt I change my IP address

http://ilvc01.ll.ustvnow.com/ilv61/pr/xxl/mp4:4AE8ETNT0USTVNOW2/playlist.m3u8?p=29&ip=12.12.12.12&ci=28800&cd=300&e=1485648536&cf=1485792536&jwt=eyJ0eZAiOiLKV1AiLCJhbGciOiJIUzI1NiJ9.eyJuIjoiMTZhYjMzIiwidCI6Im80dnA2bmdkejdraCk4eGJsbndvZHV0AXprZ3AiLCJpIjoiMWY1YjQxMzIiLCJzIjoidG50In0.K18GLySeP8-liH4w00ZmTaAbgCVbwhJTPR-vPspqZrY&h=09bc69dae149be1fed17a9815c5f098f


they seem very different apart from the channel ID and teh line proceeding jwt=
