### ISSUE TITLE
Only works in browser tried different user agents to no aval 

### ISSUE THREAD

**Issue by mrpromo999** [mathsgrinds/ustvnow-iptv-m3u-playlist#8]
Script works great , But even using the following user agents I cannot get the links to play in any player or even on my flussonic 

"AppleCoreMedia/1.0.0.8C148 (iPad; U; CPU OS 4_2_1 like Mac OS X; en_us)"
Mozilla/5.0 (iPad; CPU OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) CriOS/30.0.1599.12 Mobile/11A465 Safari/8536.25 (3B92C18B-D9DE-4CB7-A02A-22FD2AF17C8F)

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393

thank you any advice

**Comment by mathsgrinds** [comment]
Yeah, I don't know, a few weeks ago I noticed the USTVnow addon stopped working and my script couln't scrape anymore. You think it is an user-agent problem?
I've not looked into fixing this yet.

**Comment by mrpromo999** [comment]
script works fine !  yeh its user agent but listen I can get the links I have another script I'm working on maybe we can work together on it it works and pulls the mp4 links and can play without useragent    but I need little help do you have skype ill send u a copy

**Comment by mathsgrinds** [comment]
Hi there, I do indeed have Skype, we’ll try to work something out, what timezone are you in? I’m in Ireland.

**Comment by mrpromo999** [comment]
I'm in London my script is working fine just needs a quick look and get missing channels

**Comment by TVGPlayer** [comment]
Hello, I'm new to running Python scripts. Is your ustvnow script still working? How can I get video links to all the channels? Thanks!

**Comment by mathsgrinds** [comment]
Hi there, I’ll be online at around about 9 if you want to skype, my username is stepheneasley-walsh

 

Thanks J

**Comment by mathsgrinds** [comment]
Hi, something changed with the USTVnow website a few weeks ago, so problems.

**Comment by mrpromo999** [comment]
excellent added you message me when you are free

**Comment by TVGPlayer** [comment]
Is your ustvnow script still working? How can I get video links to all the channels? Thanks!

**Comment by mathsgrinds** [comment]
Great, thanks, got swamped last night with house stuff.

**Comment by mathsgrinds** [comment]
At the moment not, but TVGPlayer things he might get it working again. We will work on it sometime.

**Comment by Wolverine2018** [comment]
hi, is script working? i get the following errors

Traceback (most recent call last):
  File "main.py", line 98, in <module>
    Ustvnow(username, password)
  File "main.py", line 62, in Ustvnow
    j = json.loads(html)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
