### ISSUE TITLE
ImportError: No module named requests

### ISSUE THREAD

**Issue by tharsim** [mathsgrinds/ustvnow-iptv-m3u-playlist#9]
Hello. I'm trying to run the script but it returns me the following error: 

> ImportError: No module named requests

Any idea of what's wrong with me trying to run it?
Thanks

**Comment by mathsgrinds** [comment]
Hi there, that message means you do not have "requests". A quick google will give you instructions on how to install the missing dependencies that is install requests. If you are on Linux it's probably something like 'sudo pip install requests' and if you are on windows there is probably a requests.exe to download.
